name: reformer-tts
channels:
  - base
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip>=20.0,<20.1
  - pytorch==1.4.0
  - torchvision==0.5.0
  - ffmpeg>=4.0,<4.1
  - torchaudio==0.4.0
  - matplotlib==3.1.3
  - pip:
    - dacite==1.4.0
    - awscli==1.18
    - boto3==1.12
    - dvc==0.88
    - Click==7
    - pytorch-lightning==0.7.6
    - PyYAML==5.1.2
    - tqdm==4.43.0
    - beautifulsoup4==4.8.2
    - requests==2.23.0
    - reformer-pytorch==0.19.1
    - demjson==2.2.4
    - scipy==1.4.1
    - ffmpeg-python==0.2.0
    - librosa==0.7.2
    - unidecode==1.1.1
    - nltk==3.4.5
    - g2p-en==2.1.0
    - pydub==0.23.1
    - neptune-client==0.4.109
    - psutil==5.7.0
    - pandas==1.0.3
    - google-cloud-storage==1.28.1
    - pytest==5.4.2
    - transformers==2.11.0
    - -e .
